---
title: "Pandemic Prepared-ness and Covid-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r load-data}
covid_data <- read.csv("https://wzb-ipi.github.io/corona/df_full.csv"
)

covid_data
```
```{r libraries}
library(tidyverse)
library(glue)
library(lubridate)
library(rms)
library(dplyr)
library(ggplot2)
```

```{r modify-dates}
covid_data <- covid_data %>%
  mutate(
    dates = ymd(glue("{year} {month} {day}"))
  )
```
```{r plot-pan-prep}
covid_data %>%
  filter(date == "2020-11-30") %>%
  ggplot(covid_data, mapping = aes(x = pandemic_prep, y = deaths_cum_per_million)) +
  geom_point() +
  stat_smooth(method = "lm") + 
  labs(title = "Relationship between Pandemic Preparedness and Deaths Per Million", 
       x = "Pandemic Preparedness", 
       y = "Cumulative Deaths per Million") +
  theme_minimal() +
   theme(title = element_text(size = 7)) 
```

```{r plot-pan-gdp}
covid_data %>%
  filter(date == "2020-11-30") %>%
  ggplot(covid_data, mapping = aes(x = pandemic_prep, y = deaths_cum_per_million, color = gdp_pc)) +
  scale_color_viridis_c() +
  geom_point() +
  stat_smooth(method = "lm") + 
  labs(title = " Pandemic Preparedness and Cumulative Deaths Per Million", 
       x = "Pandemic Preparedness", 
       y = "Cumulative Deaths per Million", 
       color = "GDP per Capita") +
  theme_minimal()+
  theme(title = element_text(size = 7))
```

```{r plot-air-travel}

covid_data %>%
  filter(date == "2020-11-30") %>%
  ggplot(covid_data, mapping = aes(x = pandemic_prep, y = deaths_cum_per_million, color = air_travel)) +
  scale_color_viridis_c() +
  geom_point() +
  stat_smooth(method = "lm") + 
  labs(title = "Pandemic Preparedness and Cumulative Deaths Per Million", 
       x = "Pandemic Preparedness", 
       y = "Cumulative Deaths per Million", 
       color = "Air Travel") +
  theme_minimal()+
  theme(title = element_text(size = 7))

covid_data %>%
  filter(date == "2020-11-30") %>%
  ggplot(covid_data, mapping = aes(x = air_travel, y = deaths_cum_per_million)) +
  geom_point() +
  stat_smooth(method = "lm") +
  labs(title = "Air Travel and Cumulative Deaths per Million",
       x = "Air Travel", 
       y = "Cumulative Deaths per Million") +
  theme_minimal()
  
```

```{r plot-share-older}
covid_data %>%
  filter(date == "2020-11-30") %>%
  ggplot(covid_data, mapping = aes(x = pandemic_prep, y = deaths_cum_per_million, color = share_older)) +
  scale_color_viridis_c() +
  geom_point() +
  stat_smooth(method = "lm") + 
  labs(title = "Pandemic Preparedness and Cumulative Deaths Per Million", 
       x = "Pandemic Preparedness", 
       y = "Cumulative Deaths per Million", 
       color = "Population 65+") +
  theme_minimal() +
   theme(title = element_text(size = 7)) 

covid_data %>%
  filter(date == "2020-11-30") %>%
  ggplot(covid_data, mapping = aes(x = share_older, y = deaths_cum_per_million)) +
  geom_point() +
  stat_smooth(method = "lm") +
  labs(title = "Older Populations and Cumulative Deaths per Million",
       x = "Share of Population Over 65", 
       y = "Cumulative Deaths per Million") +
  theme_minimal()

```

```{r plot-gdp-air-travel}
covid_data %>%
  filter(date == "2020-11-30") %>%
  ggplot(covid_data, mapping = aes(x = gdp_pc, y = air_travel)) +
  geom_point() +
  stat_smooth(method = "lm") +
  labs(title = "Relationship between GDP per Capita and Air Travel",
       y = "Air Travel", 
       x = "GDP per Capita")
```

```{r plot-combined}
covid_data %>%
  filter(date == "2020-11-30") %>%
  ggplot(covid_data, mapping = aes(x = pandemic_prep, y = deaths_cum_per_million, color = gdp_pc, alpha = air_travel)) +
  scale_color_viridis_c() +
  geom_point(size = 3) +
  stat_smooth(method = "lm") + 
  labs(title = "Relationship between Pandemic Preparedness and Deaths Per Million", 
       x = "Pandemic Preparedness", 
       y = "Cumulative Deaths per Million", 
       color = "GDP per Capita", 
       alpha = "Air Travel") +
  theme_minimal()
```

```{r age-and-air-travel}
ggplot(covid_data, mapping = aes(x = share_older, y = air_travel)) +
  geom_point() +
  stat_smooth(method = "lm")
```

